# -*- coding: utf-8 -*-
"""BA865_teamproject_generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkRkNs6gcL8clsXlwwcMEBv3CahNnECG
"""

# Mount to drive
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

# Import necessary libraries
import os
import cv2
from natsort import natsorted

def create_frame(video_folder_path,frame_folder_path):
  sorted_folder_path = natsorted(os.listdir(video_folder_path))
  total_frame = 0 #just for checking
  for filename in sorted_folder_path:
    # Get the video original folder name
    file_name = str(os.path.basename(filename)).split('_')[0]
    # Set the high, low bounds for looping
    if int(file_name) > 0 and int(file_name) < 11:
      video_path = os.path.join(video_folder_path, filename)
      video_name = os.path.basename(video_path).replace('.avi','')

      cap = cv2.VideoCapture(video_path)
      count = 0
      while True:
        # count*50 refer to 0.05 sec per frame
        cap.set(cv2.CAP_PROP_POS_MSEC,(count*50))
        ret, frame = cap.read()
        if not ret:
          break
        frame_path = os.path.join(frame_folder_path, f'{video_name}-{count+1}.jpg')
        cv2.imwrite(frame_path, frame)
        count += 1

      # Release the video capture object
      cap.release()
      total_frame += count
    elif int(file_name) > 10:
      break

  print(f'Total frame count: {total_frame}')

# Create frame from video - Train
train_folder = '/content/gdrive/MyDrive/BA865/data/train_data/'
train_frame = '/content/gdrive/MyDrive/BA865/data/train_frame/'

create_frame(train_folder,train_frame)

# Create frame from video - Test
test_folder = '/content/gdrive/MyDrive/BA865/data/test_data/'
test_frame = '/content/gdrive/MyDrive/BA865/data/test_frame/'

create_frame(test_folder,test_frame)